project:
  type: website
  resources: 
    - images/*

website:
  title: "UW RSE Nexus: The crowdsourced Research Software Engineering resource hub"
  page-navigation: true

  repo-url: https://github.com/UW-Madison-DataScience/UW-RSE-Nexus
  repo-actions: [edit]

  sidebar:
    tools:
      - icon: github
        href: https://github.com/UW-Madison-DataScience/UW-RSE-Nexus
        text: "GitHub repository"
        target: _blank # Opens a new tab
    # logo: "images/UW-RSE_Logo_Secondary_Tagline_Transparent.png"
    logo: "images/UW-RSE_Logo_Secondary_Transparent.png"

    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: "Home"

      - href: KB/Guides/How-to-contribute.qmd
        text: "How to contribute?"

      - section: "Knowledge Base"
        href: KB/index.qmd
        contents:
          - text: "Presentations"
            href: KB/Presentations/index.qmd
          - text: "Resources"
            href: KB/Resources/index.qmd
          - text: "Guides"
            href: KB/Guides/index.qmd

      - text: "Projects"
        href: Projects/index.qmd

format:
  html:
    link-external-newwindow: true # Make it so external links open a new tab
    link-external-icon: true # Make it so 'icon' in the yaml will also open a new tab
    theme:
      light: [cosmo, fonts.scss, theme.scss]
      #dark: [cosmo, fonts.scss, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto

#language:
#  repo-action-links-edit: "Improve this page"

