---
title: "UW RSE Nexus: Crowdsourced Research Software Engineer Resources"
order: 1
listing:
  type: grid
  sort-ui: false
  sort:
    - "date desc"
    #- "title asc" #desc
  image-height: 150px
  image-placeholder: "images/vincent-van-zalinge-mDohQISBnCk-unsplash.jpg"
  fields: [author, date, image, title, description, categories]
  categories: true
  date-format: "YYYY-MM-DD"
  page-size: 6
  contents:
    - "KB/*/**/*.qmd"
    - "!KB/**/index.qmd" # index files should not be listed as tiles (represent pages for resource filters)
    - "!KB/*/**/*.ipynb"

    - "Projects/*/**/*.qmd"
    - "!Projects/**/index.qmd" # index files should not be listed as tiles (represent pages for resource filters)
    - "!Projects/*/**/*.ipynb"
    
toc: false
toc-location: body
page-layout: full
title-block-banner: false
---

The UW RSE Nexus is a curated, community-driven platform designed to capture and share the collective knowledge and 
experiences of the [UW RSE community](https://hub.datascience.wisc.edu/communities/research-software-engineering-community/) 
at the University of Wisconsin Madison.

### What is a Research Software Engineer?
A Research Software Engineer is someone who works to improve research through the creation or maintenance of software.
Although job titles vary wildly, if you write scripts, make software or keep them running in a lab, research area or 
study, you can proudly call yourself a Research Software Engineer. 

### What kinds of resources are hosted on Nexus?
{{< include includes/common-resources-text.qmd >}}

### Share your knowledge on Nexus!  
This site is powered by contributions from Research Software Engineers like you. If you have a project or other
Research Software Engineering related resources to share, consider adding it to the UW RSE Nexus. Learn more on our
[How to contribute](/KB/Guides/How-to-contribute.qmd) page. 

